print("=========SPY STORY GENERATOR=========")
print()
print()
NameOfSpy = input("what is the name of your spy? ")
SpyAgency = input("What's the name of the agency you work for? ")
SecretAlias = input("What is your spy's alias/code? ")
FavouriteDrink = input("What is your Favourite drink? ")
NameOfBoss = input("What is your agency boss's name? ")
NameOfVillain =input("What is the Villain's name? ")
NameOfVillainsPet = input("What is the Villain's pet he has on his lap? ")
NameOfCriminalEmpire = input("What is the name of the criminal empire? ")
EvilPlotToTakeOverWorld = input("Name of Evil plot/plan? ")
NameOfVehicle = input("What is your vehicle? ")
NameOfGadget = input("What is your gadget? ")
WhatDoesGadgetDo = input("What does your gadget do? ")
print()
print()
print()
print()
print()
print()
print()
print()
print("on an early morning in a hotel room in London lies", NameOfSpy)
print("With a beautiful lady")
print("Suddenly the phone rings")
print(NameOfSpy,"answers the phone,'Hello,",NameOfSpy,"who is speaking?'")
print(SecretAlias,"'It's", NameOfBoss,"we need you at our office immediately'")
print("'Ok i'll be there'")
print(NameOfSpy,"jumps in his",NameOfVehicle)
print("and drives to", SpyAgency,)
print(NameOfSpy,"Enters the office of", NameOfBoss)
print("'What's wrong", NameOfBoss)
print("','there appears to be some trouble in russia again",SecretAlias)
print("There is a wealthy jewell thief who plans on taking over the world,", SecretAlias)
print("and we want you to stop him'")
print(NameOfSpy,"flicks through dossier")
print(NameOfVillain,"' now heads the master criminal empire", NameOfCriminalEmpire)
print("'")
print("'We want you to stop him", SecretAlias)
print("Meanwhile in a secret hideout", NameOfVillain,"is telling his")
print("minions of his grand plan")
print("'My grand evil plan is", EvilPlotToTakeOverWorld,"'")
print("Just as", NameOfVillain,"has revealed his plan", NameOfSpy)
print("bursts through the doors")
print("'Stop'", NameOfVillain)
print(NameOfVillain,"spins around in his chair stroking his", NameOfVillainsPet)
print(NameOfSpy,"'I'ts you'")
print("'You will never know of my plan to", EvilPlotToTakeOverWorld)
print("Damn!''")
print("'Get him'")
print(NameOfVillain,"henchmen all jump on", NameOfSpy)
print("Take him to the dungeon")
print(NameOfSpy,"Get's taken to the dungeon where he is chained up")
print("While in the dungeon our hero remembers the gadget he snook in with")
print("'right here goes',",NameOfSpy, "pulls", NameOfGadget,"out of his pocket")
print("and points it at the doors, suddenly the gadget",WhatDoesGadgetDo)
print("And the door falls open, and the chains break")
print("to which", NameOfSpy,"escapes")
print("silently creeping along the corridor, he bumps the guard on the head and")
print("climbs through the window")
print("Stops", NameOfVillain,"with his", NameOfGadget)
print("and prevents the evil plan")
print("Meanwhile, in", SpyAgency, "Hq")
print("Well done", SecretAlias,"we couldn't have done it without you")
print("Would you like a drink, to celebrate", SecretAlias,"?")
print("Yes i'll have a", FavouriteDrink,"")
print("'Shaken not stirred'", SecretAlias,"?")
print("Hahaha...No!")
print("So our hero and master spy, saved the world yet again from evil")
print("========THE END========")
